### NumPy – Arithmetic Operations

### Addition

In [1]:
import numpy as np

# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

# Performing addition using arithmetic operator
add_ans = a+b
print(add_ans)

# Performing addition using numpy function
add_ans = np.add(a, b)
print(add_ans)

# this would work
c = np.array([1, 2, 3, 4])
add_ans = a+b+c
print(add_ans)

# but here NumPy only considers the first two arrays (a and b) and ignores the third one (c).
add_ans = np.add(a, b, c)
print(add_ans)


[  7  77  23 130]
[  7  77  23 130]
[  8  79  26 134]
[  7  77  23 130]


### Subtraction

In [2]:
import numpy as np

# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

# Performing subtraction using arithmetic operator
sub_ans = a-b
print(sub_ans)

# Performing subtraction using numpy function
sub_ans = np.subtract(a, b)
print(sub_ans)


[ 3 67  3 70]
[ 3 67  3 70]


### Multiplication

In [3]:
import numpy as np

# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

# Performing multiplication using arithmetic operator
mul_ans = a*b
print(mul_ans)

# Performing multiplication using numpy function
mul_ans = np.multiply(a, b)
print(mul_ans)


[  10  360  130 3000]
[  10  360  130 3000]


### Division

In [4]:
import numpy as np

# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

# Performing division using arithmetic operators
div_ans = a/b
print(div_ans)

# Performing division using numpy functions
div_ans = np.divide(a, b)
print(div_ans)


[ 2.5        14.4         1.3         3.33333333]
[ 2.5        14.4         1.3         3.33333333]


### mod() and power() function

In [5]:
# Performing mod on two matrices
mod_ans = np.mod(a, b)
print(mod_ans)

#Performing remainder on two matrices
rem_ans=np.remainder(a,b)
print(rem_ans)

# Performing power of two matrices
pow_ans = np.power(a, b)
print(pow_ans)


[ 1  2  3 10]
[ 1  2  3 10]
[        25 1934917632  419538377          0]


### Some aggregation and statistical functions

In [9]:
a = np.array([2,4,6,8])
b = np.array([1,3,5,7])
# Getting mean of all numbers in 'a'
mean_a = np.mean(a)
print(mean_a)

# Getting average of all numbers in 'b'
mean_b = np.average(b)
print(mean_b)

# Getting sum of all numbers in 'a'
sum_a = np.sum(a)
print(sum_a)

# Getting variance of all number in 'b'
var_b = np.var(b)
print(var_b)


5.0
4.0
20
5.0
