## Create Numpy Arrays Using Lists or Tuples


In [5]:
import numpy as np

my_list = [1, 2, 3, 4, 5,6]
numpy_array = np.array(my_list)
print("Simple NumPy Array:",numpy_array)

Simple NumPy Array: [1 2 3 4 5 6]


## Initialize a Python NumPy Array Using Special Functions


## NumPy provides several built-in functions to generate arrays with specific properties.

np.zeros(): Creates an array filled with zeros.

np.ones(): Creates an array filled with ones.

np.full(): Creates an array filled with a specified value.

np.arange(): Creates an array with values that are evenly spaced within a given range.

np.linspace(): Creates an array with values that are evenly spaced over a specified interval.


In [6]:
import numpy as np

zeros_array = np.zeros((2, 3))
ones_array = np.ones((3, 3))
constant_array = np.full((2, 2), 7)
range_array = np.arange(0, 10, 2)  # start, stop, step
linspace_array = np.linspace(0, 1, 5)  # start, stop, num

print("Zero Array:","\n",zeros_array)
print("Ones Array:","\n",ones_array)
print("Constant Array:","\n",constant_array)
print("Range Array:","\n",range_array)
print("Linspace Array:","\n",linspace_array)

Zero Array: 
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Constant Array: 
 [[7 7]
 [7 7]]
Range Array: 
 [0 2 4 6 8]
Linspace Array: 
 [0.   0.25 0.5  0.75 1.  ]


## Create Python Numpy Arrays Using Random Number Generation


## NumPy provides functions to create arrays filled with random numbers.

np.random.rand(): Creates an array of specified shape and fills it with random values sampled from a uniform distribution over [0, 1).

np.random.randn(): Creates an array of specified shape and fills it with random values sampled from a standard normal distribution.

np.random.randint(): Creates an array of specified shape and fills it with random integers within a given range.


In [7]:
import numpy as np

random_array = np.random.rand(2, 3)
normal_array = np.random.randn(2, 2)
randint_array = np.random.randint(1, 10, size=(2, 3))  

print(random_array)
print(normal_array)
print(randint_array)

[[0.8733695  0.91227109 0.53303972]
 [0.1820421  0.6551971  0.05536353]]
[[-1.19704269  1.22427711]
 [-0.01460523 -1.5319301 ]]
[[2 5 1]
 [9 3 8]]


## Create Python Numpy Arrays Using Matrix Creation Routines


## NumPy provides functions to create specific types of matrices.

np.eye(): Creates an identity matrix of specified size.
np.diag(): Constructs a diagonal array.
np.zeros_like(): Creates an array of zeros with the same shape and type as a given array.
np.ones_like(): Creates an array of ones with the same shape and type as a given array.


In [10]:
import numpy as np

identity_matrix = np.eye(3)
diagonal_array = np.diag([1, 2, 3])
zeros_like_array = np.zeros_like(diagonal_array)
ones_like_array = np.ones_like(diagonal_array)

print(identity_matrix)
print(diagonal_array)
print(zeros_like_array)
print(ones_like_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


## Numpy Array Indexing


### Array Indexing in NumPy is used to access or modify specific elements of an array.

### Accessing 1D Array

In a 1D array, we can access elements using their zero-based index:


In [11]:
import numpy as np

# Create a 1D NumPy array with five elements
arr = np.array([10, 20, 30, 40, 50])

# Access and print the first element of the array
print(arr[4])

50


### Access 2-D Array

To access elements, you specify the row index first and the column index second.


In [12]:
import numpy as np 

# Define a 2D array
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Access the element at row 1, column 2 
print(matrix[1, 2])

6


### Accessing 3D Arrays

A 3D array can be visualized as a stack of 2D arrays. We need three indices:

Depth: Specifies the 2D slice.
Row: Specifies the row within the slice.
Column: Specifies the column within the row.


In [13]:
import numpy as np

cube = np.array([[[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]],
                 
                 [[10, 11, 12],
                  [13, 14, 15],
                  [16, 17, 18]]])

# Access the element at depth 1, row 2, column 0
print(cube[1, 2, 0])

16


### Slicing Arrays

We can extract a subset of elements using the start:stop:step syntax:


In [16]:
import numpy as np

# Create a 1D NumPy array with six elements
arr = np.array([0, 1, 2, 3, 4, 5])

# Use slicing to access a subset of the array
print(arr[0:5])

[0 1 2 3 4]


### For multidimensional arrays, slicing can be applied to each dimension:


In [17]:
import numpy as np

# Create a 2D NumPy array (matrix) with three rows and three columns
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Use slicing to extract a submatrix
print(matrix[0:2, 1:3])

[[2 3]
 [5 6]]
